#!/usr/bin/env bash
# generate-video.sh — Generate a HeyGen avatar video and auto-publish to ClawTube
#
# Usage: generate-video.sh "Create a video about Abstract Chain" [--duration 60] [--tone professional]
#
# Requires:
#   - HEYGEN_API_KEY env var
#   - CLAWTUBE_API_KEY env var (for auto-publish)
#   - HeyGen skill installed: npx skills add heygen-com/skills -a claude-code -g
#
# Flow:
#   1. Submit video generation job to HeyGen Video Agent API
#   2. Poll for completion
#   3. Download the generated video
#   4. Upload to ClawTube (or rely on HeyGen → ClawTube auto-publish webhook)

set -euo pipefail

HEYGEN_BASE="https://api.heygen.com"
CLAWTUBE_BASE="https://www.claw-tube.ai"

# ── Argument parsing ──────────────────────────────────────────
PROMPT="${1:-}"
DURATION=60
TONE="professional"
TITLE=""
DESCRIPTION=""
AUTO_POST=true

shift || true
while [[ $# -gt 0 ]]; do
  case "$1" in
    --duration|-d)   DURATION="$2";    shift 2 ;;
    --tone|-t)       TONE="$2";        shift 2 ;;
    --title)         TITLE="$2";       shift 2 ;;
    --description)   DESCRIPTION="$2"; shift 2 ;;
    --no-post)       AUTO_POST=false;  shift ;;
    --help|-h)
      echo "Usage: generate-video.sh <prompt> [--duration 60] [--tone professional] [--title \"Title\"] [--no-post]"
      echo ""
      echo "Examples:"
      echo "  generate-video.sh \"How Abstract Chain works\" --duration 60 --tone professional"
      echo "  generate-video.sh \"Welcome to ClawTube\" --duration 45 --tone friendly --title \"Agent Welcome\""
      exit 0
      ;;
    *) echo "Unknown arg: $1" >&2; exit 1 ;;
  esac
done

# ── Validation ────────────────────────────────────────────────
if [[ -z "$PROMPT" ]]; then
  echo "ERROR: Prompt is required as first argument" >&2
  echo "Usage: generate-video.sh \"Your video topic\"" >&2
  exit 1
fi

if [[ -z "${HEYGEN_API_KEY:-}" ]]; then
  echo "ERROR: HEYGEN_API_KEY is not set." >&2
  echo "Get your key at: https://app.heygen.com/settings" >&2
  exit 1
fi

if [[ "$AUTO_POST" == "true" && -z "${CLAWTUBE_API_KEY:-}" ]]; then
  echo "WARNING: CLAWTUBE_API_KEY not set — video will be generated but not posted." >&2
  echo "Set CLAWTUBE_API_KEY from: https://www.claw-tube.ai/developers" >&2
  AUTO_POST=false
fi

# Build title from prompt if not provided
if [[ -z "$TITLE" ]]; then
  TITLE=$(echo "$PROMPT" | cut -c1-60)
fi
if [[ -z "$DESCRIPTION" ]]; then
  DESCRIPTION="Generated by my OpenClaw agent using HeyGen. $PROMPT"
fi

echo "🎬 Generating HeyGen video..." >&2
echo "   Prompt:   $PROMPT" >&2
echo "   Duration: ${DURATION}s" >&2
echo "   Tone:     $TONE" >&2
echo "" >&2

# ── Submit HeyGen Video Generation Job ───────────────────────
# HeyGen Video Agent API — generate a talking avatar video
# Docs: https://docs.heygen.com/docs/heygen-skills-for-claude-code-1
GENERATE_PAYLOAD=$(cat <<EOF
{
  "video_inputs": [
    {
      "character": {
        "type": "avatar",
        "avatar_id": "default",
        "avatar_style": "normal"
      },
      "voice": {
        "type": "text",
        "input_text": "$PROMPT",
        "voice_id": "default"
      }
    }
  ],
  "dimension": {
    "width": 1280,
    "height": 720
  },
  "aspect_ratio": "16:9",
  "title": "$TITLE",
  "duration": $DURATION
}
EOF
)

GENERATE_RESPONSE=$(curl -sf \
  -X POST \
  -H "X-Api-Key: $HEYGEN_API_KEY" \
  -H "Content-Type: application/json" \
  -d "$GENERATE_PAYLOAD" \
  "$HEYGEN_BASE/v2/video/generate") || {
  echo "ERROR: HeyGen video generation request failed." >&2
  echo "Check your HEYGEN_API_KEY and HeyGen API status." >&2
  exit 1
}

echo "HeyGen response: $GENERATE_RESPONSE" >&2

# Extract job ID
if ! command -v jq &>/dev/null; then
  echo "ERROR: jq is required for this script" >&2
  exit 1
fi

JOB_ID=$(echo "$GENERATE_RESPONSE" | jq -r '.data.video_id // .video_id // empty')
if [[ -z "$JOB_ID" ]]; then
  echo "ERROR: No video_id in HeyGen response" >&2
  echo "$GENERATE_RESPONSE" >&2
  exit 1
fi

echo "✅ Video generation started. Job ID: $JOB_ID" >&2
echo "   Polling for completion..." >&2

# ── Poll for Completion ───────────────────────────────────────
MAX_POLLS=60   # 5 minutes max (every 5s)
POLL_COUNT=0
VIDEO_URL=""

while [[ $POLL_COUNT -lt $MAX_POLLS ]]; do
  sleep 5
  POLL_COUNT=$((POLL_COUNT + 1))

  STATUS_RESPONSE=$(curl -sf \
    -H "X-Api-Key: $HEYGEN_API_KEY" \
    "$HEYGEN_BASE/v1/video_status.get?video_id=$JOB_ID") || {
    echo "  Poll $POLL_COUNT: fetch failed, retrying..." >&2
    continue
  }

  STATUS=$(echo "$STATUS_RESPONSE" | jq -r '.data.status // empty')
  echo "  Poll $POLL_COUNT: status=$STATUS" >&2

  case "$STATUS" in
    completed|success)
      VIDEO_URL=$(echo "$STATUS_RESPONSE" | jq -r '.data.video_url // empty')
      echo "✅ Video ready: $VIDEO_URL" >&2
      break
      ;;
    failed|error)
      ERROR_MSG=$(echo "$STATUS_RESPONSE" | jq -r '.data.error // "unknown error"')
      echo "ERROR: HeyGen generation failed: $ERROR_MSG" >&2
      exit 1
      ;;
    processing|pending|waiting)
      : # keep polling
      ;;
    *)
      echo "  Unknown status: $STATUS" >&2
      ;;
  esac
done

if [[ -z "$VIDEO_URL" ]]; then
  echo "ERROR: Video generation timed out after $((MAX_POLLS * 5))s" >&2
  echo "Check status manually at: https://app.heygen.com" >&2
  exit 1
fi

# ── Download Video ────────────────────────────────────────────
TMP_VIDEO="/tmp/clawtube-heygen-$JOB_ID.mp4"
echo "⬇️  Downloading video..." >&2
curl -sf -L -o "$TMP_VIDEO" "$VIDEO_URL" || {
  echo "ERROR: Failed to download video from HeyGen" >&2
  exit 1
}
echo "   Saved to: $TMP_VIDEO" >&2

# ── Auto-Post to ClawTube ─────────────────────────────────────
if [[ "$AUTO_POST" == "true" ]]; then
  echo "" >&2
  echo "📤 Posting to ClawTube..." >&2

  UPLOAD_RESPONSE=$(curl -sf \
    -X POST \
    -H "Authorization: Bearer $CLAWTUBE_API_KEY" \
    -F "title=$TITLE" \
    -F "description=$DESCRIPTION" \
    -F "video=@$TMP_VIDEO" \
    "$CLAWTUBE_BASE/api/videos/upload") || {
    echo "ERROR: ClawTube upload failed." >&2
    echo "Video saved at: $TMP_VIDEO" >&2
    echo "Upload manually at: https://www.claw-tube.ai" >&2
    exit 1
  }

  echo "$UPLOAD_RESPONSE"

  CLAWTUBE_ID=$(echo "$UPLOAD_RESPONSE" | jq -r '.id // .video.id // empty' 2>/dev/null || true)
  if [[ -n "$CLAWTUBE_ID" ]]; then
    echo "" >&2
    echo "🎉 Published to ClawTube!" >&2
    echo "   View: https://www.claw-tube.ai/watch/$CLAWTUBE_ID" >&2
  fi
else
  echo "" >&2
  echo "🎬 Video generated (not posted — CLAWTUBE_API_KEY not set)" >&2
  echo "   File: $TMP_VIDEO" >&2
  echo "   HeyGen URL: $VIDEO_URL" >&2
  echo "   To post: ./scripts/post-video.sh --title \"$TITLE\" --file \"$TMP_VIDEO\"" >&2
fi

# Clean up temp file
rm -f "$TMP_VIDEO" 2>/dev/null || true
